function other_vector = prob2_other_vector(in1,in2)
%PROB2_OTHER_VECTOR
%    OTHER_VECTOR = PROB2_OTHER_VECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Feb-2020 11:27:04

M = in2(2,:);
dtheta = in1(4,:);
dx = in1(3,:);
theta = in1(2,:);
x = in1(1,:);
other_vector = [M.*sin(theta).*(-9.81e2./1.0e2);dtheta.*-7.0e1+dx.*7.0e1-theta.*2.0e2+x.*2.0e2-M.*x.*cos(theta).*(9.81e2./1.0e2)];
