function W_hessian = prob1_W_hessian(L,M,m,theta1,theta2)
%PROB1_W_HESSIAN
%    W_HESSIAN = PROB1_W_HESSIAN(L,M,M,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Feb-2020 15:11:19

t2 = cos(theta1);
t3 = L.*M.*t2.*2.0;
t4 = L.^2;
t5 = cos(theta2);
t6 = L.*M.*t5;
t7 = theta1-theta2;
t8 = cos(t7);
t9 = M.*t4.*t8;
W_hessian = reshape([M.*2.0+m,t3,t6,t3,M.*t4.*2.0,t9,t6,t9,M.*t4],[3,3]);
