function other_vector = prob1_other_vector(L,M,dtheta1,dtheta2,dx,theta1,theta2,x)
%PROB1_OTHER_VECTOR
%    OTHER_VECTOR = PROB1_OTHER_VECTOR(L,M,DTHETA1,DTHETA2,DX,THETA1,THETA2,X)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Feb-2020 15:11:20

t2 = sin(theta1);
t3 = L.^2;
t4 = dtheta2.^2;
t5 = theta1-theta2;
t6 = sin(t5);
t7 = sin(theta2);
t8 = dtheta1.^2;
other_vector = [-dx-x.*1.0e1+L.*M.*t2.*t8.*2.0+L.*M.*t4.*t7;dtheta1.*(L.*M.*dx.*t2.*2.0+M.*dtheta2.*t3.*t6)-L.*M.*t2.*(9.81e2./5.0e1)-M.*t3.*t4.*t6-L.*M.*dtheta1.*dx.*t2.*2.0-M.*dtheta1.*dtheta2.*t3.*t6;dtheta2.*(L.*M.*dx.*t7-M.*dtheta1.*t3.*t6)-L.*M.*t7.*(9.81e2./1.0e2)+M.*t3.*t6.*t8-L.*M.*dtheta2.*dx.*t7+M.*dtheta1.*dtheta2.*t3.*t6];
